eclipse-edc/Technology-Aws

- DEPENDENCIES
- extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3BucketProvisionedResource.java
- extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGenerator.java
- extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3StatusChecker.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/validation/S3DataAddressCredentialsValidationRule.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/validation/S3DataAddressValidationRule.java
Fixes compile errors that arose due to the `getProperty` -> `getStringProperty` transition in the `DataAddress` class.
compile errors
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
> fix: use the getStringProperty method of the DataAddress

- .github/workflows/verify.yaml
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/AwsClientProvider.java
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/AwsClientProviderConfiguration.java
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/AwsClientProviderImpl.java
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/S3BucketSchema.java
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/S3ClientRequest.java
- extensions/common/aws/aws-s3-test/README.md
- extensions/common/aws/aws-s3-test/src/testFixtures/java/org/eclipse/edc/aws/s3/testfixtures/AbstractS3Test.java
- extensions/common/aws/aws-s3-test/src/testFixtures/java/org/eclipse/edc/aws/s3/testfixtures/S3TestClient.java
- extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3StatusCheckerIntegrationTest.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactoryTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java
PR adds possibility to specify 'endpointOverride' property in DataAddress.
So that it's possible to push data into different instance of S3 compatible storage than configured via dataplane's properties.
Change mostly based on previous PR (https://github.com/eclipse-edc/Connector/pull/1904) by @reisman234, recreated due to changes in project structure.
Closes https://github.com/eclipse-edc/Technology-Aws/issues/24
> feat: make endpointOverride configurable by DataAddress

- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSource.java
Fix compile issue on `S3DataSource`
not compiling
> chore: fix compile issue

- DEPENDENCIES
- README.md
- docs/developer/decision-records/README.md
The links in the main readme were updated as they were broken. To fix some broken links, the docs/developer/decision-records directory had to be created. A readme was placed in the latter to populate the folder.
To make links work again.
No further notes.
No issues was created.
> chore: fix broken links

- DEPENDENCIES
- extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtension.java
- extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtensionTest.java
_Briefly describe WHAT your pr changes, which features it adds/modifies._
_Briefly state why the change was necessary._
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
> fix: compile errors after EDC token refactor

- DEPENDENCIES
- extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGenerator.java
- extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGeneratorTest.java
_Briefly describe WHAT your pr changes, which features it adds/modifies._
_Briefly state why the change was necessary._
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
> fix: adapt to EDC upstream

- DEPENDENCIES
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/S3BucketSchema.java
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/S3DataAddressValidatorExtension.java
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/validation/S3DestinationDataAddressValidator.java
- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/validation/S3SourceDataAddressValidator.java
- extensions/common/aws/aws-s3-core/src/test/java/org/eclipse/edc/aws/s3/S3DestinationDataAddressValidatorExtensionTest.java
- extensions/common/aws/aws-s3-core/src/test/java/org/eclipse/edc/aws/s3/validation/S3DestinationDataAddressValidatorTest.java
- extensions/common/aws/aws-s3-core/src/test/java/org/eclipse/edc/aws/s3/validation/S3SourceDataAddressValidatorTest.java
- extensions/common/aws/aws-s3-test/src/testFixtures/java/org/eclipse/edc/aws/s3/testfixtures/AbstractS3Test.java
- extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGeneratorTest.java
- extensions/data-plane/data-plane-aws-s3/README.md
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/DataPlaneS3Extension.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSink.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSource.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/TestFunctions.java
- Introduces the `objectName` property to store the S3 object name
- Refactors `keyName` to exclusively handle secret aliases
- Renames `keyPrefix` to `objectPrefix`
- Destination object(s) naming decision based on `Part` list size.
- Updates documentation
- Updates tests
To align with the existing behavior of `TransferProcessManagerImpl`, which defaults to using `keyName` for fetching secret values, rather than introducing a new property configuration specifically for holding the secret alias, a more effective approach would be to introduce an `objectName` property to store the S3 object name. This modification aims to enhance consistency and also alignment between the `AWS` and `Azure` platforms.
Closes #211
> feat: enable reusable credentials for S3 integration

- DEPENDENCIES
- extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3BucketProvisionedResourceTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactoryTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java
fix compile issue after type manager refactor upstream
> chore: fix compile issue after type manager refactor upstream

- .github/workflows/nighly.yaml
- .github/workflows/verify.yaml
- DEPENDENCIES
- build.gradle.kts
- gradle.properties
This PR adds a nightly release workflow to the tech repo
decouple tech repositories
- a successful run (manual trigger) is here: https://github.com/eclipse-edc/Technology-Aws/actions/runs/9220460096. Ireverted that commit to `upstream/main` afterwards...
Closes <https://github.com/eclipse-edc/Release/issues/17>
> feat(ci): add nightly build job

- DEPENDENCIES
- extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3BucketResourceDefinition.java
- extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3BucketResourceDefinitionTest.java
Add missing deserialization annotations
fix bug
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
Closes #338 
> fix: S3BucketResourceDefinition deserialization

- extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVault.java
- extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultTest.java
This PR updates the AWS Vault implementation to match the behavior of HashiCorp Vault. Previously, the `store` method in the AWS Vault implementation only created new secrets. With this update, the method now supports both creating and updating secrets, aligning it with the behavior of HashiCorp Vault.
This update is required because the recent addition of the [Secrets Manager API](https://github.com/eclipse-edc/Connector/pull/4138) introduces the capability to update secrets. As a result, the AWS Vault implementation must be updated to handle secret updates in addition to secret creation.
Closes #373
> feat: Modifies the AWS vault implementation to update existing secrets

- .github/workflows/release-tech-aws.yml
- DEPENDENCIES
Switches to creating the tags and merge commit using plain bash (as opposed to: GH actions)
There were weird, unreproducible and undebuggable `"merge conflict"` errors in the past. Also, bash scripts are easier to debug and replicate locally.
- successful test in my fork: https://github.com/paullatzelsperger/Technology-Aws/actions/runs/10056788484
> feat(ci): create tag and merge commit manually

- .github/workflows/publish.yaml
- .github/workflows/release-tech-aws.yml
- .github/workflows/verify.yaml
- DEPENDENCIES
This PR adds a temporary fix to update the `gradle/libs.version.toml` version catalog before a version is published. 
Specifically, it passes the version string to `verify.yaml`, so that tests are executed using the given upstream EDC modules, and it updates `gradle.properties`, `gradle/libs.versions.toml` and `DEPENDENCIES` before the Maven artefacts are published.
In addition, the release job (`release-tech-aws.yaml`) only bumps the version if it was a "release" version (not a hotfix/bugfix or a snapshot).
employ a temporary fix until a restructuring of the release workflow can be implemented.
I intentionally did not extract the `sed` command in a re-usable action, because it is a temporary fix anyway, and it is better if it sticks out like a sore thumb
Closes # <-- _insert Issue number …
> fix(ci): set version before tests, publishing

- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/DataPlaneS3Extension.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/DataPlaneS3ExtensionTest.java
This PR aims to fix the addition of AmazonS3 destination type by the generator service in the initialiaztion of the extension. 
With the removal of sourcetypes properties from the dataplane selector logic, now the destination type must be registered during the boot and so this change allows that for the AmazonS3 type.
Tests were added for existing class to promote quality and consistency.
Closes https://github.com/eclipse-edc/Technology-Aws/issues/401
> Use generator service to register AmazonS3 destination type

- extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVault.java
- extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultTest.java
This PR updates the AWS Vault implementation to match the behavior of HashiCorp Vault. Previously, the store method in the AWS Vault implementation only created new secrets. With this update, the method now supports both creating and updating secrets, aligning it with the behavior of HashiCorp Vault.
This update is required because the recent addition of the [Secrets Manage API](https://github.com/eclipse-edc/Connector/pull/4138 ) introduces the capability to update secrets. As a result, the AWS Vault implementation must be updated to handle secret updates in addition to secret creation.
This is a backport from [PR](https://github.com/eclipse-edc/Technology-Aws/pull/379)
> feat: Modifies the AWS vault implementation to update existing secrets (Backport)

- DEPENDENCIES
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSource.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceTest.java
Stop closing the client when `DataSource` is closed
client could be part of a pool and get reused for other transfers (common case on the source side of transfer).
it's the actual flow that should be interrupted eventually. this PR doesn't take care of this, it's just patching the bug in the simplest way possible.
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
Closes #455 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_et …
> fix: avoid to close client on data source closure

- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/DataPlaneS3Extension.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactoryTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java
Deserializes the secret obtained from the vault to either an `AwsSecretToken` or an `AwsTemporarySecretToken` depending on whether it contains a `sessionToken` field or not.
To allow both the usage of static and temporary credentials with the S3 data plane. Previously, the secret was always deserialized directly to an `AwsTemporarySecretToken`, which caused the transfer to fail if static credentials were used.
The code for deserializing the secret has been duplicated for `S3DataSourceFactory` and `S3DataSinkFactory` for now, as also the code for creating the S3 client request is duplicated. Refactoring to remove these duplications should be done in another PR.
Closes #457
> fix(dataplane): deserialize secret depending on content

- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactoryTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java
_Briefly describe WHAT your pr changes, which features it adds/modifies._
_Briefly state why the change was necessary._
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
> ci: fix compilation

- extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/AwsClientProviderImpl.java
- extensions/common/aws/aws-s3-core/src/test/java/org/eclipse/edc/aws/s3/AwsClientProviderImplTest.java
Defines a default key that will be used by the `AwsClientProviderImpl` to cache a created `IamAsyncClient` if no `endpointOverride` property is supplied in the client request. The default key is only used for IAM clients, as all other client types are region-bound and for them, a combination of `region` and `endpointOverride` properties is used as the key, thus no NullPointerException is raised there on a missing `endpointOverride`.
Previously only the `endpointOverride` property was used as the key for storing `IamAsyncClients`, causing a NullPointerException if no `endpointOverride` was supplied.
I noticed that we do not yet have any tests for the `AwsClientProviderImpl`. I added only the relevant tests for the fix for now, but we should create a follow-up issue to add additional tests …
> fix: iamAsyncClient without endpointOverride

- extensions/data-plane/data-plane-aws-s3/README.md
Updates the examples and documentation regarding secret tokens in the `data-plane-aws-s3` `README`. Namely, adds the following:
- `edctype` field in JSON examples
- `accessKeyId` and `secretAccessKey` fields in JSON example for `AwsTemporarySecretToken`
- a note regarding the expiration time for temporary tokens
Previously, the JSON examples were incomplete, possibly causing confusion/errors when strictly following the `README`.
Closes #491
> docs: update examples for secret tokens in data plane README

- extensions/common/vault/vault-aws/build.gradle.kts
- extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtension.java
- extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtensionTest.java
`AwsSecretsManagerVaultExtension` do not allow to override AWS endpoint. However, `S3CoreExtension` allows it. So, I implements endpoint overrides in `AwsSecretsManagerVault` using `edc.aws.endpoint.override` the same param of `S3CoreExtension`.
For AWS-compatible services like localstack.
Closes #486
> feat: allow endpoint overrides in AwsSecretsManagerVault

- extensions/data-plane/data-plane-aws-s3/README.md
Adds a section to the `README` of `data-plane-aws-s3`, that describes the AWS permissions required for the user/role used by the data plane.
The `README` does currently not contain any information regarding the required AWS permissions. For the sake of completeness, these should be added here.
To improve readability, I adjusted the headers/sections a bit, as previously every section was under "About this module", causing a quite nested header/section structure.
> docs: add required AWS permissions to data plane README

- docs/developer/decision-records/2025-02-13-s3-to-s3-transfers-within-aws/README.md
- docs/developer/decision-records/README.md
Following up on [this discussion](https://github.com/eclipse-edc/Technology-Aws/discussions/517), adds a decision record for implementing an addition to the S3 data plane, that will allow for running S3-to-S3 transfers within the AWS infrastructure.
To reduce transfer costs.
me
> docs: decision record for S3-to-S3 transfers within AWS

- extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3ProvisionPipeline.java
- extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3BucketProvisionerTest.java
Ensures validation of S3 bucket existence during provision to only try to create it if it does not already exist.
Right now, if the bucket exists, then an Exception is thrown during provision. This impedes of (for example) copying data to the target bucket since provision cannot happen.
Closes #552
> feat: Create a S3 bucket during provision only if one does not previously exist

- extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGenerator.java
- extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGeneratorTest.java
Adds a null check for the `dataDestination` in `canGenerate()` of `S3ConsumerResourceDefinitionGenerator`.
to avoid NullPointerException on PULL transfers
me
Closes #578
> fix: NullPointerException in S3ConsumerResourceDefinitionGenerator

- extensions/common/validator/validator-data-address-s3/src/main/java/org/eclipse/edc/aws/s3/validator/S3SourceDataAddressValidator.java
- extensions/data-plane/data-plane-aws-s3/README.md
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSource.java
- extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java
- extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceTest.java
Add the FolderName attribute to the S3DataSource, which allows the user to specify the exact name in the destination that will be retrieved using FolderName and Prefix as filters.
With the implementation of this feature, users can now select assets as before, but by combining both attributes, take control of the outcome file(s) name(s).
For a quick example, let's consider an S3 bucket on the provider side with two files (file1 and file2) and three different requests. The non-relevant attributes to this feature showcase will be omitted.
Path in Source (S3): 
folder/prefix/file1
folder/prefix/file2
Request1 :    OBJECT_PREFIX = "folder/prefix/"
Output1: [folder/prefix/file1, folder/prefix/file2]
Request2:    FOLDER_NAME = "folder/" && OBJECT_PREFIX = "prefix/"
Output2: [prefix/file1, …
> feat: Add FolderName attribute to S3DataSource
